- name: install app
  hosts: all
  vars:
    clone_path: "{{ repo_clone_dir | default('./weatherapp') }}"
    front_env: "{{ front_env_file | default('../frontend/.env') }}"
    back_env: "{{ back_env_file | default('../backend/.env') }}"

  tasks:
    - name: install docker
      ansible.builtin.package:
        name: docker
        state: latest

    - name: install docker
      ansible.builtin.package:
        name: docker-compose
        state: latest
     
    - name: clone app repository
      ansible.builtin.git:
        repo: https://github.com/Tyberiusz-Maniok/eficode-recruitment.git
        dest: "{{ clone_path }}"
        single_branch: yes
        version: main

    - name: copy frontend env file
      ansible.builtin.copy:
        src: "{{ front_env }}"
        dest: "{{ clone_path + '/frontend/.env' }}"
        mode: u=r,g=r,o=r
      ignore_errors: true

    - name: copy backend env file
      ansible.builtin.copy:
        src: "{{ back_env }}"
        dest: "{{ clone_path + '/backend/.env' }}"
        mode: u=r,g=r,o=r
      ignore_errors: true
